name: CommandTweaks
version: '${project.version}'
main: com.core.commandtweaks.CommandTweaks
api-version: '1.21'
load: STARTUP
authors: [ JoeyBalardeta ]
description: A plugin for multiplayer Minecraft servers.

commands:
  ct: