name: CommandTweaks
version: '${project.version}'
main: com.core.commandtweaks.Commandtweaks
api-version: 1.19
load: STARTUP
authors: [ JoeyBalardeta, DanielGeva, HyperSkys ]
description: A plugin for multiplayer Minecraft servers.
