name: CommandTweaks
version: '${project.version}'
main: com.core.commandtweaks.CommandTweaks
api-version: '1.20'
load: STARTUP
authors: [ JoeyBalardeta, DanielGeva ]
description: A plugin for multiplayer Minecraft servers.

commands:
  ct: